### ISSUE TITLE
Document `public` folder

### ISSUE THREAD

**Issue by PMunch** [HapticX/hapdoc#23]
Tried to use HappyX today but I'm a bit confused. Basically I just wanted to try out a very simple SSG with some static HTML/CSS files and a route to catch the input from a form. I created my project using `hpx create --name test --kind SSG` and it created the project structure for me. I dropped some files into the `public` folder but the server doesn't seem to serve these files. Looked at the examples and the only one which appears to do this is the `nim-lang` one and it appears to serve them with the `public` prefix on, however trying that didn't make it serve my file either. So I'm not sure if I need to do something to make HappyX serve the files from the `public` directory or not, it doesn't log requests either so I don't really know what's going on..

**Comment by Ethosa** [comment]
@PMunch it's not happyx repo 👀

please, give me more info:
- happyx version
- project structure (folder screenshot)
- code where you use public folder

**Comment by PMunch** [comment]
Oh sorry, I must've had multiple repos open and put thin in the wrong place. I will resubmit this with the additional data in the HappyX repo.
